### PR TITLE
Ukiyo-e filter - Krishna

### PR DESCRIPTION
**Pull request by krishnagajjala**
I added a Ukiyo-e filter following the steps in the README and generated the necessary assets as well using the given code and cycle_gan/ukiyoe2photo dataset

### CODE REVIEW

**Comment by BlueBlaze6335** [comment]
Hey @krishnagajjala great work. But we haven't started our open source journey yet. Can you wait for a few days ?? We will merge your pr when JWOC starts. If you want to contribute , please register as a mentee at [jwoc.tech](https://jwoc.tech/) !!

**Comment by BlueBlaze6335** [comment]
@krishnagajjala did you register at JWOC ??

**Comment by krishnagajjala** [comment]
No sorry, I don't plan to register, I was just doing this for fun

**Comment by BlueBlaze6335** [comment]
Then i am very sorry to let you know that your PR will not be merged , but do not be sad , because you can be a contributor after this event !! Looking forward to work with you !

**Pull request closed without merging**
